# Generated by Django 3.2.3 on 2021-05-24 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_db_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_step',
            old_name='Case_id',
            new_name='case_id',
        ),
    ]
