# Generated by Django 3.2.3 on 2021-05-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0011_db_project_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_step',
            name='public_header',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
