# Generated by Django 3.2.3 on 2021-05-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0013_db_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_project_host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('host', models.TextField(null=True)),
            ],
        ),
    ]
