# Generated by Django 3.2.3 on 2021-06-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0014_db_project_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_global_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('user_id', models.CharField(max_length=10, null=True)),
                ('data', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DB_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=10, null=True)),
                ('api_method', models.CharField(max_length=10, null=True)),
                ('api_url', models.CharField(max_length=1000, null=True)),
                ('api_header', models.CharField(max_length=1000, null=True)),
                ('api_host', models.CharField(max_length=100, null=True)),
                ('body_method', models.CharField(max_length=20, null=True)),
                ('api_body', models.CharField(max_length=1000, null=True)),
                ('sign', models.CharField(max_length=10, null=True)),
                ('set', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='db_step',
            old_name='case_id',
            new_name='Case_id',
        ),
        migrations.AddField(
            model_name='db_project',
            name='global_datas',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='db_project',
            name='user_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='db_step',
            name='api_login',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
