# Generated by Django 3.2.3 on 2021-06-14 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0015_auto_20210603_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_sql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_name', models.CharField(max_length=20, null=True)),
                ('sql_des', models.CharField(max_length=50, null=True)),
                ('sql_content', models.CharField(max_length=200, null=True)),
                ('is_handle_table', models.BooleanField(verbose_name='是否分库分表')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Myapp.db_project')),
            ],
        ),
    ]
