# Generated by Django 3.2.3 on 2021-06-15 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0016_db_sql'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=20, null=True)),
                ('db_host', models.CharField(max_length=20, null=True)),
                ('db_port', models.CharField(max_length=10, null=True)),
                ('db_user', models.CharField(max_length=20, null=True)),
                ('db_password', models.CharField(max_length=50, null=True)),
                ('db_charset', models.CharField(max_length=10, null=True)),
                ('db_database', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='db_sql',
            name='is_handle_table',
        ),
        migrations.AddField(
            model_name='db_sql',
            name='sql_db',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Myapp.dbs'),
        ),
    ]
