# Generated by Django 3.2.3 on 2021-06-15 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0017_auto_20210615_0916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DBs',
            new_name='DB_database',
        ),
    ]
