# Generated by Django 3.2.3 on 2021-06-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0018_rename_dbs_db_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_database',
            name='db_port',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
