# Generated by Django 3.2.3 on 2021-06-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0019_alter_db_database_db_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_database',
            name='db_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
